//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StockBeheerModel", "FK_Component_Leverancier", "Leverancier", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SamStock.Database.Leverancier), "Component", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SamStock.Database.Component), true)]
[assembly: EdmRelationshipAttribute("StockBeheerModel", "FK_PedalComponent_Component", "Component", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SamStock.Database.Component), "PedalComponent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SamStock.Database.PedalComponent), true)]
[assembly: EdmRelationshipAttribute("StockBeheerModel", "FK_PedalComponent_Pedal", "Pedal", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SamStock.Database.Pedal), "PedalComponent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SamStock.Database.PedalComponent), true)]

#endregion

namespace SamStock.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StockBeheerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StockBeheerEntities object using the connection string found in the 'StockBeheerEntities' section of the application configuration file.
        /// </summary>
        public StockBeheerEntities() : base("name=StockBeheerEntities", "StockBeheerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockBeheerEntities object.
        /// </summary>
        public StockBeheerEntities(string connectionString) : base(connectionString, "StockBeheerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockBeheerEntities object.
        /// </summary>
        public StockBeheerEntities(EntityConnection connection) : base(connection, "StockBeheerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Component> Component
        {
            get
            {
                if ((_Component == null))
                {
                    _Component = base.CreateObjectSet<Component>("Component");
                }
                return _Component;
            }
        }
        private ObjectSet<Component> _Component;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Leverancier> Leverancier
        {
            get
            {
                if ((_Leverancier == null))
                {
                    _Leverancier = base.CreateObjectSet<Leverancier>("Leverancier");
                }
                return _Leverancier;
            }
        }
        private ObjectSet<Leverancier> _Leverancier;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pedal> Pedal
        {
            get
            {
                if ((_Pedal == null))
                {
                    _Pedal = base.CreateObjectSet<Pedal>("Pedal");
                }
                return _Pedal;
            }
        }
        private ObjectSet<Pedal> _Pedal;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PedalComponent> PedalComponent
        {
            get
            {
                if ((_PedalComponent == null))
                {
                    _PedalComponent = base.CreateObjectSet<PedalComponent>("PedalComponent");
                }
                return _PedalComponent;
            }
        }
        private ObjectSet<PedalComponent> _PedalComponent;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Component EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComponent(Component component)
        {
            base.AddObject("Component", component);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Leverancier EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLeverancier(Leverancier leverancier)
        {
            base.AddObject("Leverancier", leverancier);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pedal EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPedal(Pedal pedal)
        {
            base.AddObject("Pedal", pedal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PedalComponent EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPedalComponent(PedalComponent pedalComponent)
        {
            base.AddObject("PedalComponent", pedalComponent);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockBeheerModel", Name="Component")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Component : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Component object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="naam">Initial value of the Naam property.</param>
        /// <param name="minimumStock">Initial value of the MinimumStock property.</param>
        /// <param name="hoeveelheid">Initial value of the Hoeveelheid property.</param>
        /// <param name="stocknr">Initial value of the Stocknr property.</param>
        /// <param name="prijs">Initial value of the Prijs property.</param>
        /// <param name="leverancierId">Initial value of the LeverancierId property.</param>
        public static Component CreateComponent(global::System.Int32 id, global::System.String naam, global::System.Int32 minimumStock, global::System.Int32 hoeveelheid, global::System.String stocknr, global::System.Decimal prijs, global::System.Int32 leverancierId)
        {
            Component component = new Component();
            component.Id = id;
            component.Naam = naam;
            component.MinimumStock = minimumStock;
            component.Hoeveelheid = hoeveelheid;
            component.Stocknr = stocknr;
            component.Prijs = prijs;
            component.LeverancierId = leverancierId;
            return component;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naam
        {
            get
            {
                return _Naam;
            }
            set
            {
                OnNaamChanging(value);
                ReportPropertyChanging("Naam");
                _Naam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Naam");
                OnNaamChanged();
            }
        }
        private global::System.String _Naam;
        partial void OnNaamChanging(global::System.String value);
        partial void OnNaamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MinimumStock
        {
            get
            {
                return _MinimumStock;
            }
            set
            {
                OnMinimumStockChanging(value);
                ReportPropertyChanging("MinimumStock");
                _MinimumStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinimumStock");
                OnMinimumStockChanged();
            }
        }
        private global::System.Int32 _MinimumStock;
        partial void OnMinimumStockChanging(global::System.Int32 value);
        partial void OnMinimumStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hoeveelheid
        {
            get
            {
                return _Hoeveelheid;
            }
            set
            {
                OnHoeveelheidChanging(value);
                ReportPropertyChanging("Hoeveelheid");
                _Hoeveelheid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hoeveelheid");
                OnHoeveelheidChanged();
            }
        }
        private global::System.Int32 _Hoeveelheid;
        partial void OnHoeveelheidChanging(global::System.Int32 value);
        partial void OnHoeveelheidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stocknr
        {
            get
            {
                return _Stocknr;
            }
            set
            {
                OnStocknrChanging(value);
                ReportPropertyChanging("Stocknr");
                _Stocknr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stocknr");
                OnStocknrChanged();
            }
        }
        private global::System.String _Stocknr;
        partial void OnStocknrChanging(global::System.String value);
        partial void OnStocknrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Prijs
        {
            get
            {
                return _Prijs;
            }
            set
            {
                OnPrijsChanging(value);
                ReportPropertyChanging("Prijs");
                _Prijs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prijs");
                OnPrijsChanged();
            }
        }
        private global::System.Decimal _Prijs;
        partial void OnPrijsChanging(global::System.Decimal value);
        partial void OnPrijsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LeverancierId
        {
            get
            {
                return _LeverancierId;
            }
            set
            {
                OnLeverancierIdChanging(value);
                ReportPropertyChanging("LeverancierId");
                _LeverancierId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LeverancierId");
                OnLeverancierIdChanged();
            }
        }
        private global::System.Int32 _LeverancierId;
        partial void OnLeverancierIdChanging(global::System.Int32 value);
        partial void OnLeverancierIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Opmerkingen
        {
            get
            {
                return _Opmerkingen;
            }
            set
            {
                OnOpmerkingenChanging(value);
                ReportPropertyChanging("Opmerkingen");
                _Opmerkingen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Opmerkingen");
                OnOpmerkingenChanged();
            }
        }
        private global::System.String _Opmerkingen;
        partial void OnOpmerkingenChanging(global::System.String value);
        partial void OnOpmerkingenChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockBeheerModel", "FK_Component_Leverancier", "Leverancier")]
        public Leverancier Leverancier
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Leverancier>("StockBeheerModel.FK_Component_Leverancier", "Leverancier").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Leverancier>("StockBeheerModel.FK_Component_Leverancier", "Leverancier").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Leverancier> LeverancierReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Leverancier>("StockBeheerModel.FK_Component_Leverancier", "Leverancier");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Leverancier>("StockBeheerModel.FK_Component_Leverancier", "Leverancier", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockBeheerModel", "FK_PedalComponent_Component", "PedalComponent")]
        public EntityCollection<PedalComponent> PedalComponent_1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PedalComponent>("StockBeheerModel.FK_PedalComponent_Component", "PedalComponent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PedalComponent>("StockBeheerModel.FK_PedalComponent_Component", "PedalComponent", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockBeheerModel", Name="Leverancier")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Leverancier : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Leverancier object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="naam">Initial value of the Naam property.</param>
        public static Leverancier CreateLeverancier(global::System.Int32 id, global::System.String naam)
        {
            Leverancier leverancier = new Leverancier();
            leverancier.Id = id;
            leverancier.Naam = naam;
            return leverancier;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naam
        {
            get
            {
                return _Naam;
            }
            set
            {
                OnNaamChanging(value);
                ReportPropertyChanging("Naam");
                _Naam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Naam");
                OnNaamChanged();
            }
        }
        private global::System.String _Naam;
        partial void OnNaamChanging(global::System.String value);
        partial void OnNaamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adres
        {
            get
            {
                return _Adres;
            }
            set
            {
                OnAdresChanging(value);
                ReportPropertyChanging("Adres");
                _Adres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adres");
                OnAdresChanged();
            }
        }
        private global::System.String _Adres;
        partial void OnAdresChanging(global::System.String value);
        partial void OnAdresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Site
        {
            get
            {
                return _Site;
            }
            set
            {
                OnSiteChanging(value);
                ReportPropertyChanging("Site");
                _Site = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Site");
                OnSiteChanged();
            }
        }
        private global::System.String _Site;
        partial void OnSiteChanging(global::System.String value);
        partial void OnSiteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockBeheerModel", "FK_Component_Leverancier", "Component")]
        public EntityCollection<Component> Component
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Component>("StockBeheerModel.FK_Component_Leverancier", "Component");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Component>("StockBeheerModel.FK_Component_Leverancier", "Component", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockBeheerModel", Name="Pedal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pedal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pedal object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="margin">Initial value of the Margin property.</param>
        public static Pedal CreatePedal(global::System.Int32 id, global::System.String name, global::System.Decimal price, global::System.Decimal margin)
        {
            Pedal pedal = new Pedal();
            pedal.Id = id;
            pedal.Name = name;
            pedal.Price = price;
            pedal.Margin = margin;
            return pedal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Margin
        {
            get
            {
                return _Margin;
            }
            set
            {
                OnMarginChanging(value);
                ReportPropertyChanging("Margin");
                _Margin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Margin");
                OnMarginChanged();
            }
        }
        private global::System.Decimal _Margin;
        partial void OnMarginChanging(global::System.Decimal value);
        partial void OnMarginChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockBeheerModel", "FK_PedalComponent_Pedal", "PedalComponent")]
        public EntityCollection<PedalComponent> PedalComponent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PedalComponent>("StockBeheerModel.FK_PedalComponent_Pedal", "PedalComponent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PedalComponent>("StockBeheerModel.FK_PedalComponent_Pedal", "PedalComponent", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockBeheerModel", Name="PedalComponent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PedalComponent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PedalComponent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="componentId">Initial value of the ComponentId property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="pedalId">Initial value of the PedalId property.</param>
        public static PedalComponent CreatePedalComponent(global::System.Int32 id, global::System.Int32 componentId, global::System.Int32 number, global::System.Int32 pedalId)
        {
            PedalComponent pedalComponent = new PedalComponent();
            pedalComponent.Id = id;
            pedalComponent.ComponentId = componentId;
            pedalComponent.Number = number;
            pedalComponent.PedalId = pedalId;
            return pedalComponent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ComponentId
        {
            get
            {
                return _ComponentId;
            }
            set
            {
                OnComponentIdChanging(value);
                ReportPropertyChanging("ComponentId");
                _ComponentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComponentId");
                OnComponentIdChanged();
            }
        }
        private global::System.Int32 _ComponentId;
        partial void OnComponentIdChanging(global::System.Int32 value);
        partial void OnComponentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PedalId
        {
            get
            {
                return _PedalId;
            }
            set
            {
                OnPedalIdChanging(value);
                ReportPropertyChanging("PedalId");
                _PedalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PedalId");
                OnPedalIdChanged();
            }
        }
        private global::System.Int32 _PedalId;
        partial void OnPedalIdChanging(global::System.Int32 value);
        partial void OnPedalIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockBeheerModel", "FK_PedalComponent_Component", "Component")]
        public Component Component
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Component>("StockBeheerModel.FK_PedalComponent_Component", "Component").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Component>("StockBeheerModel.FK_PedalComponent_Component", "Component").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Component> ComponentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Component>("StockBeheerModel.FK_PedalComponent_Component", "Component");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Component>("StockBeheerModel.FK_PedalComponent_Component", "Component", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockBeheerModel", "FK_PedalComponent_Pedal", "Pedal")]
        public Pedal Pedal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedal>("StockBeheerModel.FK_PedalComponent_Pedal", "Pedal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedal>("StockBeheerModel.FK_PedalComponent_Pedal", "Pedal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pedal> PedalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedal>("StockBeheerModel.FK_PedalComponent_Pedal", "Pedal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pedal>("StockBeheerModel.FK_PedalComponent_Pedal", "Pedal", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
