//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StockBeheerModel", "FK_Component_Leverancier", "Leverancier", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SamStock.Database.Leverancier), "Component", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SamStock.Database.Component), true)]

#endregion

namespace SamStock.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StockBeheerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StockBeheerEntities object using the connection string found in the 'StockBeheerEntities' section of the application configuration file.
        /// </summary>
        public StockBeheerEntities() : base("name=StockBeheerEntities", "StockBeheerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockBeheerEntities object.
        /// </summary>
        public StockBeheerEntities(string connectionString) : base(connectionString, "StockBeheerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StockBeheerEntities object.
        /// </summary>
        public StockBeheerEntities(EntityConnection connection) : base(connection, "StockBeheerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Component> Component
        {
            get
            {
                if ((_Component == null))
                {
                    _Component = base.CreateObjectSet<Component>("Component");
                }
                return _Component;
            }
        }
        private ObjectSet<Component> _Component;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Leverancier> Leverancier
        {
            get
            {
                if ((_Leverancier == null))
                {
                    _Leverancier = base.CreateObjectSet<Leverancier>("Leverancier");
                }
                return _Leverancier;
            }
        }
        private ObjectSet<Leverancier> _Leverancier;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Component EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComponent(Component component)
        {
            base.AddObject("Component", component);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Leverancier EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLeverancier(Leverancier leverancier)
        {
            base.AddObject("Leverancier", leverancier);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockBeheerModel", Name="Component")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Component : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Component object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="naam">Initial value of the Naam property.</param>
        /// <param name="minimumStock">Initial value of the MinimumStock property.</param>
        /// <param name="hoeveelheid">Initial value of the Hoeveelheid property.</param>
        /// <param name="stocknr">Initial value of the Stocknr property.</param>
        /// <param name="prijs">Initial value of the Prijs property.</param>
        /// <param name="leverancierId">Initial value of the LeverancierId property.</param>
        public static Component CreateComponent(global::System.Int32 id, global::System.String naam, global::System.Int32 minimumStock, global::System.Int32 hoeveelheid, global::System.String stocknr, global::System.Decimal prijs, global::System.Int32 leverancierId)
        {
            Component component = new Component();
            component.Id = id;
            component.Naam = naam;
            component.MinimumStock = minimumStock;
            component.Hoeveelheid = hoeveelheid;
            component.Stocknr = stocknr;
            component.Prijs = prijs;
            component.LeverancierId = leverancierId;
            return component;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naam
        {
            get
            {
                return _Naam;
            }
            set
            {
                OnNaamChanging(value);
                ReportPropertyChanging("Naam");
                _Naam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Naam");
                OnNaamChanged();
            }
        }
        private global::System.String _Naam;
        partial void OnNaamChanging(global::System.String value);
        partial void OnNaamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MinimumStock
        {
            get
            {
                return _MinimumStock;
            }
            set
            {
                OnMinimumStockChanging(value);
                ReportPropertyChanging("MinimumStock");
                _MinimumStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinimumStock");
                OnMinimumStockChanged();
            }
        }
        private global::System.Int32 _MinimumStock;
        partial void OnMinimumStockChanging(global::System.Int32 value);
        partial void OnMinimumStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hoeveelheid
        {
            get
            {
                return _Hoeveelheid;
            }
            set
            {
                OnHoeveelheidChanging(value);
                ReportPropertyChanging("Hoeveelheid");
                _Hoeveelheid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hoeveelheid");
                OnHoeveelheidChanged();
            }
        }
        private global::System.Int32 _Hoeveelheid;
        partial void OnHoeveelheidChanging(global::System.Int32 value);
        partial void OnHoeveelheidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Stocknr
        {
            get
            {
                return _Stocknr;
            }
            set
            {
                OnStocknrChanging(value);
                ReportPropertyChanging("Stocknr");
                _Stocknr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Stocknr");
                OnStocknrChanged();
            }
        }
        private global::System.String _Stocknr;
        partial void OnStocknrChanging(global::System.String value);
        partial void OnStocknrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Prijs
        {
            get
            {
                return _Prijs;
            }
            set
            {
                OnPrijsChanging(value);
                ReportPropertyChanging("Prijs");
                _Prijs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prijs");
                OnPrijsChanged();
            }
        }
        private global::System.Decimal _Prijs;
        partial void OnPrijsChanging(global::System.Decimal value);
        partial void OnPrijsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LeverancierId
        {
            get
            {
                return _LeverancierId;
            }
            set
            {
                OnLeverancierIdChanging(value);
                ReportPropertyChanging("LeverancierId");
                _LeverancierId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LeverancierId");
                OnLeverancierIdChanged();
            }
        }
        private global::System.Int32 _LeverancierId;
        partial void OnLeverancierIdChanging(global::System.Int32 value);
        partial void OnLeverancierIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Opmerkingen
        {
            get
            {
                return _Opmerkingen;
            }
            set
            {
                OnOpmerkingenChanging(value);
                ReportPropertyChanging("Opmerkingen");
                _Opmerkingen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Opmerkingen");
                OnOpmerkingenChanged();
            }
        }
        private global::System.String _Opmerkingen;
        partial void OnOpmerkingenChanging(global::System.String value);
        partial void OnOpmerkingenChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockBeheerModel", "FK_Component_Leverancier", "Leverancier")]
        public Leverancier Leverancier
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Leverancier>("StockBeheerModel.FK_Component_Leverancier", "Leverancier").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Leverancier>("StockBeheerModel.FK_Component_Leverancier", "Leverancier").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Leverancier> LeverancierReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Leverancier>("StockBeheerModel.FK_Component_Leverancier", "Leverancier");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Leverancier>("StockBeheerModel.FK_Component_Leverancier", "Leverancier", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StockBeheerModel", Name="Leverancier")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Leverancier : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Leverancier object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="naam">Initial value of the Naam property.</param>
        public static Leverancier CreateLeverancier(global::System.Int32 id, global::System.String naam)
        {
            Leverancier leverancier = new Leverancier();
            leverancier.Id = id;
            leverancier.Naam = naam;
            return leverancier;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naam
        {
            get
            {
                return _Naam;
            }
            set
            {
                OnNaamChanging(value);
                ReportPropertyChanging("Naam");
                _Naam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Naam");
                OnNaamChanged();
            }
        }
        private global::System.String _Naam;
        partial void OnNaamChanging(global::System.String value);
        partial void OnNaamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adres
        {
            get
            {
                return _Adres;
            }
            set
            {
                OnAdresChanging(value);
                ReportPropertyChanging("Adres");
                _Adres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adres");
                OnAdresChanged();
            }
        }
        private global::System.String _Adres;
        partial void OnAdresChanging(global::System.String value);
        partial void OnAdresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Site
        {
            get
            {
                return _Site;
            }
            set
            {
                OnSiteChanging(value);
                ReportPropertyChanging("Site");
                _Site = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Site");
                OnSiteChanged();
            }
        }
        private global::System.String _Site;
        partial void OnSiteChanging(global::System.String value);
        partial void OnSiteChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StockBeheerModel", "FK_Component_Leverancier", "Component")]
        public EntityCollection<Component> Component
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Component>("StockBeheerModel.FK_Component_Leverancier", "Component");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Component>("StockBeheerModel.FK_Component_Leverancier", "Component", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
