//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMStock.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public Component()
        {
            this.ComponentsOfPedals = new HashSet<ComponentsOfPedals>();
            this.ComponentsOfComponentOrders = new HashSet<ComponentsOfComponentOrder>();
            this.ComponentsOfComponentOrderDeliveries = new HashSet<ComponentsOfComponentOrderDelivery>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int MinimumStock { get; set; }
        public int Stock { get; set; }
        public string StockNumber { get; set; }
        public decimal Price { get; set; }
        public int SupplierId { get; set; }
        public string Remarks { get; set; }
        public string ItemCode { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<ComponentsOfPedals> ComponentsOfPedals { get; set; }
        public virtual ICollection<ComponentsOfComponentOrder> ComponentsOfComponentOrders { get; set; }
        public virtual ICollection<ComponentsOfComponentOrderDelivery> ComponentsOfComponentOrderDeliveries { get; set; }
    }
}
