//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMStock.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentOrder
    {
        public ComponentOrder()
        {
            this.ComponentsOfComponentOrders = new HashSet<ComponentsOfComponentOrder>();
            this.ComponentOrderDeliveries = new HashSet<ComponentOrderDelivery>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<ComponentsOfComponentOrder> ComponentsOfComponentOrders { get; set; }
        public virtual ICollection<ComponentOrderDelivery> ComponentOrderDeliveries { get; set; }
    }
}
