//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMStock.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentOrderDelivery
    {
        public ComponentOrderDelivery()
        {
            this.ComponentsOfComponentOrderDeliveries = new HashSet<ComponentsOfComponentOrderDelivery>();
        }
    
        public int Id { get; set; }
        public int ComponentOrderId { get; set; }
        public System.DateTime DateArrived { get; set; }
    
        public virtual ComponentOrder ComponentOrder { get; set; }
        public virtual ICollection<ComponentsOfComponentOrderDelivery> ComponentsOfComponentOrderDeliveries { get; set; }
    }
}
